(TeX-add-style-hook "chap-skel-mtk"
 (lambda ()
    (TeX-run-style-hooks
     "hyperref"
     "colorlinks"
     "overpic"
     "shorttoc"
     "fncychap"
     "Bjarne"
     "subfig"
     "enumerate"
     "mathpazo"
     "sc"
     "fontenc"
     "T1"
     "floatflt"
     "marvosym"
     "multicol"
     "pict2e"
     "chappg"
     "array"
     "color"
     "graphicx"
     "amssymb"
     "amsmath"
     "amsthm"
     "latex2e"
     "scrreprt10"
     "scrreprt"
     "10pt"
     "letterpaper"
     "chapterprefix"
     "macros"
     "probability")))

