(TeX-add-style-hook "induction"
 (lambda ()
    (LaTeX-add-labels
     "ch:induction"
     "s:induction:intro"
     "s:induction:posintsord"
     "s:induction:statements"
     "s:induction:bincoeffs"
     "fig:pascal"
     "s:induction:recursion"
     "fig:induction:lines-regions"
     "s:induction:gcd"
     "thm:division"
     "thm:euclideanalg"
     "thm:gcd-dioph"
     "s:induction:induction"
     "s:induction:inductdefs"
     "s:induction:proofs"
     "prop:sumints"
     "fig:squaregrid"
     "prop:sumodd"
     "fig:oddsum3"
     "prop:sum-bincoeffs"
     "s:induction:exercises")))

