(TeX-add-style-hook "introduction"
 (lambda ()
    (LaTeX-add-labels
     "ch:intro"
     "s:intro:intro"
     "s:intro:enum"
     "fig:intro:necklace"
     "s:intro:graph"
     "fig:graphdata"
     "fig:connectedgraph"
     "ex:radiostations"
     "fig:radiostations"
     "s:intro:number"
     "ex:collatz"
     "tab:intro:partsof8"
     "s:intro:geom"
     "fig:linesregions"
     "fig:crossingedges"
     "s:intro:opt"
     "fig:wgraph-1"
     "fig:spantree-1"
     "s:intro:sudoku"
     "fig:sudoku"
     "s:intro:closing")))

