(TeX-add-style-hook "networkflow"
 (lambda ()
    (LaTeX-add-labels
     "ch:networkflow"
     "s:networkflow:intro"
     "fig:networkflow:network"
     "fig:networkflow:netflow"
     "thm:networkflow:flowleqcut"
     "networkflow:spare"
     "networkflow:used"
     "exa:networkflow:augpath"
     "prop:networkflow:update"
     "exa:networkflow:delta"
     "fig:networkflow:smallnet"
     "s:networkflow:example"
     "fig:networkflow:updated-flow"
     "fig:networkflow:flow4"
     "fig:networkflow:invalid"
     "fig:networkflow:network_ex"
     "fig:networkflow:augpath_ex"
     "ex:networkflow:update"
     "ex:networkflow:do-update"
     "fig:networkflow:network_find_flow1"
     "fig:networkflow:network_find_flow2")))

