(TeX-add-style-hook "polya"
 (lambda ()
    (LaTeX-add-labels
     "ch:polya"
     "s:polya:square"
     "fig:polya:squares"
     "tab:polya:fixed-square"
     "s:polya:perm-groups"
     "ss:polya:perm-groups:rep"
     "fig:polya:perm-digraph"
     "ss:polya:perm-groups:mult"
     "s:polya:burnside"
     "prop:polya:sum-stabs"
     "lem:polya:burnside"
     "s:polya:polya"
     "ss:polya:polya:cycle-index"
     "tab:polya:square-cycles"
     "ss:polya:polya:full"
     "theorem:polya:polya"
     "s:polya:apps"
     "ss:polya:scales"
     "fig:polya:scales"
     "ss:polya:isomers"
     "tab:polya:benzene"
     "ss:polya:graphs"
     "fig:polya:graphs"
     "s:polya:ex"
     "ex:polya:perm-rep"
     "fig:polya:pentagon"
     "ex:polya:cyclic12"
     "ex:polya:perm-pairs"
     "ex:polya:graphs5-pt1"
     "fig:polya:TTT")))

